/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Negocio.SistemaNotas;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author madar
 */
public class Principal extends javax.swing.JFrame {
    
    
    private SistemaNotas notas=new SistemaNotas();

    /**
     * Creates new form Principal
     */
    public Principal() {
        
        initComponents();
        this.setLocationRelativeTo(null);
          this.getContentPane().setBackground(Color.WHITE);
          JOptionPane.showMessageDialog(null, "Recuerde que los datos de entrada deben estar separados por saltos de líneas y cada nota con el carácter ;", "Importante", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        btnCargarNotas = new javax.swing.JButton();
        btnMostrarNotas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnMetodo1 = new javax.swing.JButton();
        btnMetodo2 = new javax.swing.JButton();
        btnMetodo4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal-Sistema Notas");
        setBackground(new java.awt.Color(255, 255, 255));

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        jScrollPane1.setViewportView(txtEntrada);

        btnCargarNotas.setText("Cargar Notas");
        btnCargarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarNotasActionPerformed(evt);
            }
        });

        btnMostrarNotas.setText("Mostrar Notas");
        btnMostrarNotas.setEnabled(false);
        btnMostrarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarNotasActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Speedy_Gonzales.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/acme.jpg"))); // NOI18N

        btnMetodo1.setText("Metodo 1");
        btnMetodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo1ActionPerformed(evt);
            }
        });

        btnMetodo2.setText("Metodo 2");
        btnMetodo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo2ActionPerformed(evt);
            }
        });

        btnMetodo4.setText("Metodo 4");
        btnMetodo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo4ActionPerformed(evt);
            }
        });

        jButton1.setText("Metodo 3");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCargarNotas)
                                .addGap(18, 18, 18)
                                .addComponent(btnMetodo1)
                                .addGap(35, 35, 35)
                                .addComponent(btnMetodo2)
                                .addGap(34, 34, 34)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(btnMetodo4))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMostrarNotas)
                        .addGap(611, 611, 611)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCargarNotas)
                            .addComponent(btnMetodo1)
                            .addComponent(btnMetodo2)
                            .addComponent(btnMetodo4)
                            .addComponent(jButton1))))
                .addGap(27, 27, 27)
                .addComponent(btnMostrarNotas)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarNotasActionPerformed
        // TODO add your handling code here:
        
        String misNotas=this.txtEntrada.getText();
        notas.cargarNotas(misNotas);
        this.txtEntrada.setText("Notas Cargadas");
        this.btnMostrarNotas.setEnabled(true);
        
        
    }//GEN-LAST:event_btnCargarNotasActionPerformed

    private void btnMostrarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarNotasActionPerformed
        // TODO add your handling code here:
        this.txtEntrada.setText(this.notas.listarEstudiantes());
    }//GEN-LAST:event_btnMostrarNotasActionPerformed

    private void btnMetodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo1ActionPerformed
        // TODO add your handling code here:
        this.txtEntrada.setText(this.notas.promedio());
    }//GEN-LAST:event_btnMetodo1ActionPerformed

    private void btnMetodo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo2ActionPerformed
        // TODO add your handling code here:
        this.txtEntrada.setText(this.notas.reprobaron());
    }//GEN-LAST:event_btnMetodo2ActionPerformed

    private void btnMetodo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo4ActionPerformed
        // TODO add your handling code here:
        this.txtEntrada.setText(this.notas.notaDefinitva());
    }//GEN-LAST:event_btnMetodo4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtEntrada.setText(notas.mostrarCantQuices());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargarNotas;
    private javax.swing.JButton btnMetodo1;
    private javax.swing.JButton btnMetodo2;
    private javax.swing.JButton btnMetodo4;
    private javax.swing.JButton btnMostrarNotas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtEntrada;
    // End of variables declaration//GEN-END:variables
}
